version: '3'


services:
 frontend:
   build:
     context: .
     dockerfile: ./hadiya-front/Dockerfile
   image: angular-build
   restart: unless-stopped
   networks:
     - internalnet
 fnginx:
   image: nginx:latest
   container_name: my-frontend-nginx-container
   volumes:
     - ./hadiya-front/conf.d:/etc/nginx/conf.d
   depends_on:
     - frontend
   ports:
     - "8080:80"
   networks:
     - internalnet


networks:
 internalnet:
   driver: bridge

